export * from './Hero'
export * from './OurStudio'
export * from './Pricing'
export * from './TestimonialCarousel'
export * from './ContactForm'
export * from './Location'
export * from './InstagramFeed'
export * from './Footer'